#pragma once
enum COLLISION_TYPE
{
	COLLISION_TYPE_GROUND,
	COLLISION_TYPE_ENEMY,
	COLLISION_TYPE_BUTTERFLY,
	COLLISION_TYPE_ITEM,
	COLLISION_TYPE_BARRIER_FOR_ENEMY,
	COLLISION_TYPE_LADDER,
	COLLISION_TYPE_BEGIN_LADDER,
	COLLISION_TYPE_GATE,
	COLLISION_TYPE_BOSS,


	
	COLLISION_TYPE_WEAPON,
	COLLISION_TYPE_WEAPON_ENEMY,
	COLLISION_TYPE_PLAYER,
	

	COLLISION_TYPE_COUNT
};

