#pragma once
enum COLLISION_TYPE
{
	COLLISION_TYPE_GROUND,
	COLLISION_TYPE_ENEMY,
	COLLISION_TYPE_STATIC_OBJECT,
	COLLISION_TYPE_ITEM,
	COLLISION_TYPE_BARRIER_FOR_ENEMY,
	COLLISION_TYPE_PLAYER,
	COLLISION_TYPE_WEAPON,

	COLLISION_TYPE_COUNT
};

