enum COLLISION_TYPE
{
	COLLISION_TYPE_GROUND,
	COLLISION_TYPE_PLAYER,
	COLLISION_TYPE_ENEMY,
	COLLISION_TYPE_STATIC_OBJECT,
	COLLISION_ITEM,

	COLLISION_TYPE_COUNT
};

struct CollisionTypeCollide
{
	COLLISION_TYPE COLLISION_TYPE_1;
	COLLISION_TYPE COLLISION_TYPE_2;
};